# Generated by Django 5.1 on 2025-07-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Laboratory Investigation / Scan',
                'verbose_name_plural': 'Laboratory Investigation / Scan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.appointment',),
        ),
    ]
